### ISSUE TITLE
404 on My Workspaces

### ISSUE THREAD

**Issue by bill-anderson** [devinit/opendevdata#95]
![jud2](https://cloud.githubusercontent.com/assets/3491562/5895887/24f7a8fa-a53c-11e4-8898-35663d0a2649.PNG)

**Comment by miclovich** [comment]
system restart from previous issue (and server software upgrade)

**Comment by bill-anderson** [comment]
When you solve a ticket can you add a comment - "Done" and reassign to me. I will then check and close
